# Conjunto de Ejercicios - Gauss-Jacobi y Gauss-Seidel

## Primer Ejercicio

1. **Encuentre las primeras dos iteraciones del método de Jacobi para los siguientes sistemas lineales, por medio de $𝐱(𝟎) = 0$:**

In [50]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [51]:
%autoreload 2

In [52]:
from src.iterative_methods import gauss_jacobi
from src.iterative_methods import gauss_seidel

Primero se establece un valor inicial de cero como se indica y una tolerancia arbitraria de $10^{-6}$ y un número elevado de iteraciones para la convergencia.

In [53]:
tol = 1e-6
max_iter = 1000

### a.
$$
3x_1 - x_2 + x_3 = 1, \\
3x_1 + 6x_2 + 2x_3 = 0, \\
3x_1 + 3x_2 + 7x_3 = 4.
$$


In [54]:
import numpy as np
A = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
b = np.array([1, 0, 4])
x0 = [0, 0, 0]

x_jacobi, tray_jacobi = gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_jacobi

[02-05 12:44:06][INFO] i= 0 x: [[0. 0. 0.]]
[02-05 12:44:06][INFO] i= 1 x: [[0.33333333 0.         0.57142857]]
[02-05 12:44:06][INFO] i= 2 x: [[ 0.14285714 -0.35714286  0.42857143]]
[02-05 12:44:06][INFO] i= 3 x: [[ 0.07142857 -0.21428571  0.66326531]]
[02-05 12:44:06][INFO] i= 4 x: [[ 0.04081633 -0.25680272  0.63265306]]
[02-05 12:44:06][INFO] i= 5 x: [[ 0.03684807 -0.23129252  0.66399417]]
[02-05 12:44:06][INFO] i= 6 x: [[ 0.03490444 -0.23975543  0.6547619 ]]
[02-05 12:44:06][INFO] i= 7 x: [[ 0.03516089 -0.23570619  0.65922185]]
[02-05 12:44:06][INFO] i= 8 x: [[ 0.03502399 -0.23732106  0.65737656]]
[02-05 12:44:06][INFO] i= 9 x: [[ 0.03510079 -0.23663751  0.65812732]]
[02-05 12:44:06][INFO] i= 10 x: [[ 0.03507839 -0.23692617  0.65780145]]
[02-05 12:44:06][INFO] i= 11 x: [[ 0.03509079 -0.23680635  0.65793476]]
[02-05 12:44:06][INFO] i= 12 x: [[ 0.0350863  -0.23685698  0.65787809]]
[02-05 12:44:06][INFO] i= 13 x: [[ 0.03508831 -0.23683585  0.65790172]]
[02-05 12:44:06][INFO] i= 14 x: 

array([[ 0.03508774],
       [-0.23684191],
       [ 0.65789495]])

### b.
$$
10x_1 - x_2 = 9, \\
-x_1 + 10x_2 - 2x_3 = 7, \\
-2x_2 + 10x_3 = 6.
$$


In [55]:
import numpy as np
A = np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]])
b = np.array([9, 7, 6])
x0 = [0, 0, 0]

x_jacobi, tray_jacobi = gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_jacobi

[02-05 12:44:06][INFO] i= 0 x: [[0. 0. 0.]]
[02-05 12:44:06][INFO] i= 1 x: [[0.9 0.7 0.6]]
[02-05 12:44:06][INFO] i= 2 x: [[0.97 0.91 0.74]]
[02-05 12:44:06][INFO] i= 3 x: [[0.991 0.945 0.782]]
[02-05 12:44:06][INFO] i= 4 x: [[0.9945 0.9555 0.789 ]]
[02-05 12:44:06][INFO] i= 5 x: [[0.99555 0.95725 0.7911 ]]
[02-05 12:44:06][INFO] i= 6 x: [[0.995725 0.957775 0.79145 ]]
[02-05 12:44:06][INFO] i= 7 x: [[0.9957775 0.9578625 0.791555 ]]
[02-05 12:44:06][INFO] i= 8 x: [[0.99578625 0.95788875 0.7915725 ]]
[02-05 12:44:06][INFO] i= 9 x: [[0.99578888 0.95789313 0.79157775]]
[02-05 12:44:06][INFO] i= 10 x: [[0.99578931 0.95789444 0.79157862]]


array([[0.99578944],
       [0.95789466],
       [0.79157889]])

### c.
$$
10x_1 + 5x_2 = 6, \\
5x_1 + 10x_2 - 4x_3 = 25, \\
-4x_2 + 8x_3 - x_4 = -11, \\
-x_3 + 5x_4 = -11.
$$

In [56]:
import numpy as np
x0 = [0, 0, 0, 0]
A = np.array([[10,5,0,0], [5,10,-4,0], [0,-4,8,-1], [0,0,-1,5]])
b = np.array([6,25,-11,-11])

x_jacobi, tray_jacobi = gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_jacobi

[02-05 12:44:06][INFO] i= 0 x: [[0. 0. 0. 0.]]
[02-05 12:44:06][INFO] i= 1 x: [[ 0.6    2.5   -1.375 -2.2  ]]
[02-05 12:44:06][INFO] i= 2 x: [[-0.65   1.65  -0.4   -2.475]]
[02-05 12:44:06][INFO] i= 3 x: [[-0.225     2.665    -0.859375 -2.28    ]]
[02-05 12:44:06][INFO] i= 4 x: [[-0.7325    2.26875  -0.3275   -2.371875]]
[02-05 12:44:06][INFO] i= 5 x: [[-0.534375    2.73525    -0.53710938 -2.2655    ]]
[02-05 12:44:06][INFO] i= 6 x: [[-0.767625    2.55234375 -0.2905625  -2.30742188]]
[02-05 12:44:06][INFO] i= 7 x: [[-0.67617187  2.7675875  -0.38725586 -2.2581125 ]]
[02-05 12:44:06][INFO] i= 8 x: [[-0.78379375  2.68318359 -0.27347031 -2.27745117]]
[02-05 12:44:06][INFO] i= 9 x: [[-0.7415918   2.78250875 -0.3180896  -2.25469406]]
[02-05 12:44:06][INFO] i= 10 x: [[-0.79125437  2.74356006 -0.26558238 -2.26361792]]
[02-05 12:44:06][INFO] i= 11 x: [[-0.77178003  2.78939423 -0.28617221 -2.25311648]]
[02-05 12:44:06][INFO] i= 12 x: [[-0.79469712  2.77142113 -0.26194244 -2.25723444]]
[02-05 12:

array([[-0.797647  ],
       [ 2.79529364],
       [-0.25882359],
       [-2.25176481]])

### d.
$$
4x_1 + x_2 + x_3 + x_5 = 6, \\
-x_1 - 3x_2 + x_3 + x_4 = 6, \\
2x_1 + x_2 + 5x_3 - x_4 - x_5 = 6, \\
-x_1 - x_2 - x_3 + 4x_4 = 6, \\
2x_2 - x_3 + x_4 + 4x_5 = 6.
$$

In [57]:
import numpy as np
x0 = [0, 0, 0, 0, 0]
A = np.array([[4,1,2,0,1], [-1,-3,1,1,0], [2,1,5,-1,-1], [-1,-1,-1,4,0], [2,-1,1,0,4]])
b = np.array([6,6,6,6,6])

x_jacobi, tray_jacobi = gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_jacobi

[02-05 12:44:06][INFO] i= 0 x: [[0. 0. 0. 0. 0.]]
[02-05 12:44:06][INFO] i= 1 x: [[ 1.5 -2.   1.2  1.5  1.5]]
[02-05 12:44:06][INFO] i= 2 x: [[ 1.025 -1.6    1.6    1.675 -0.05 ]]
[02-05 12:44:06][INFO] i= 3 x: [[ 1.1125  -1.25     1.435    1.75625  0.1875 ]]
[02-05 12:44:06][INFO] i= 4 x: [[ 1.048125   -1.30708333  1.39375     1.824375    0.2725    ]]
[02-05 12:44:06][INFO] i= 5 x: [[ 1.06177083 -1.27666667  1.46154167  1.78369792  0.30072917]]
[02-05 12:44:06][INFO] i= 6 x: [[ 1.01321354 -1.27217708  1.44751042  1.81166146  0.2845625 ]]
[02-05 12:44:06][INFO] i= 7 x: [[ 1.02314844 -1.25134722  1.46839479  1.79713672  0.31347135]]
[02-05 12:44:06][INFO] i= 8 x: [[ 1.00027157 -1.25253898  1.46313168  1.810049    0.30849028]]
[02-05 12:44:06][INFO] i= 9 x: [[ 1.00444633 -1.24236363  1.47410702  1.80271607  0.32094655]]
[02-05 12:44:06][INFO] i= 10 x: [[ 0.99330076 -1.24254108  1.47142672  1.80904743  0.31865917]]
[02-05 12:44:06][INFO] i= 11 x: [[ 0.99525712 -1.23760887  1.47672923  1.8

array([[ 0.9863023 ],
       [-1.23287728],
       [ 1.4794517 ],
       [ 1.80821894],
       [ 0.32876663]])

## Segundo Ejercicio

2. **Repita el ejercicio 1 usando el método de Gauss-Seidel**

### a.
$$
3x_1 - x_2 + x_3 = 1, \\
3x_1 + 6x_2 + 2x_3 = 0, \\
3x_1 + 3x_2 + 7x_3 = 4.
$$


In [58]:
import numpy as np
A = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
b = np.array([1, 0, 4])
x0 = [0, 0, 0]

x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_seidel

[02-05 12:44:06][INFO] i= 0 x: [[0. 0. 0.]]
[02-05 12:44:06][INFO] i= 1 x: [[ 0.33333333 -0.16666667  0.5       ]]
[02-05 12:44:06][INFO] i= 2 x: [[ 0.11111111 -0.22222222  0.61904762]]
[02-05 12:44:06][INFO] i= 3 x: [[ 0.05291005 -0.23280423  0.64852608]]
[02-05 12:44:06][INFO] i= 4 x: [[ 0.03955656 -0.23595364  0.65559875]]
[02-05 12:44:06][INFO] i= 5 x: [[ 0.0361492  -0.23660752  0.65733928]]
[02-05 12:44:06][INFO] i= 6 x: [[ 0.03535107 -0.23678863  0.65775895]]
[02-05 12:44:06][INFO] i= 7 x: [[ 0.03515081 -0.23682839  0.65786182]]
[02-05 12:44:06][INFO] i= 8 x: [[ 0.03510326 -0.23683891  0.6578867 ]]
[02-05 12:44:06][INFO] i= 9 x: [[ 0.03509146 -0.2368413   0.65789279]]
[02-05 12:44:06][INFO] i= 10 x: [[ 0.03508864 -0.23684191  0.65789426]]


array([[ 0.03508794],
       [-0.23684206],
       [ 0.65789462]])

### b.
$$
10x_1 - x_2 = 9, \\
-x_1 + 10x_2 - 2x_3 = 7, \\
-2x_2 + 10x_3 = 6.
$$


In [59]:
import numpy as np
A = np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]])
b = np.array([9, 7, 6])
x0 = [0, 0, 0]

x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_seidel

[02-05 12:44:06][INFO] i= 0 x: [[0. 0. 0.]]
[02-05 12:44:06][INFO] i= 1 x: [[0.9   0.79  0.758]]
[02-05 12:44:06][INFO] i= 2 x: [[0.979  0.9495 0.7899]]
[02-05 12:44:06][INFO] i= 3 x: [[0.99495  0.957475 0.791495]]
[02-05 12:44:06][INFO] i= 4 x: [[0.9957475  0.95787375 0.79157475]]
[02-05 12:44:06][INFO] i= 5 x: [[0.99578737 0.95789369 0.79157874]]
[02-05 12:44:06][INFO] i= 6 x: [[0.99578937 0.95789468 0.79157894]]


array([[0.99578947],
       [0.95789473],
       [0.79157895]])

### c.
$$
10x_1 + 5x_2 = 6, \\
5x_1 + 10x_2 - 4x_3 = 25, \\
-4x_2 + 8x_3 - x_4 = -11, \\
-x_3 + 5x_4 = -11.
$$

In [60]:
import numpy as np
A = np.array([[10,5,0,0], [5,10,-4,0], [0,-4,8,-1], [0,0,-1,5]])
b = np.array([6,25,-11,-11])
x0 = [0, 0, 0, 0]

x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_seidel

[02-05 12:44:06][INFO] i= 0 x: [[0. 0. 0. 0.]]
[02-05 12:44:06][INFO] i= 1 x: [[ 0.6    2.2   -0.275 -2.255]]
[02-05 12:44:06][INFO] i= 2 x: [[-0.5       2.64     -0.336875 -2.267375]]
[02-05 12:44:06][INFO] i= 3 x: [[-0.72        2.72525    -0.29579687 -2.25915938]]
[02-05 12:44:06][INFO] i= 4 x: [[-0.762625    2.76299375 -0.27589805 -2.25517961]]
[02-05 12:44:06][INFO] i= 5 x: [[-0.78149687  2.78038922 -0.26670284 -2.25334057]]
[02-05 12:44:06][INFO] i= 6 x: [[-0.79019461  2.78841617 -0.26245949 -2.2524919 ]]
[02-05 12:44:06][INFO] i= 7 x: [[-0.79420808  2.79212025 -0.26050136 -2.25210027]]
[02-05 12:44:06][INFO] i= 8 x: [[-0.79606012  2.79382952 -0.25959778 -2.25191956]]
[02-05 12:44:06][INFO] i= 9 x: [[-0.79691476  2.79461827 -0.25918081 -2.25183616]]
[02-05 12:44:06][INFO] i= 10 x: [[-0.79730913  2.79498224 -0.2589884  -2.25179768]]
[02-05 12:44:06][INFO] i= 11 x: [[-0.79749112  2.7951502  -0.25889961 -2.25177992]]
[02-05 12:44:06][INFO] i= 12 x: [[-0.7975751   2.79522771 -0.25885

array([[-0.79764674],
       [ 2.79529382],
       [-0.25882369],
       [-2.25176474]])

### d.
$$
4x_1 + x_2 + x_3 + x_5 = 6, \\
-x_1 - 3x_2 + x_3 + x_4 = 6, \\
2x_1 + x_2 + 5x_3 - x_4 - x_5 = 6, \\
-x_1 - x_2 - x_3 + 4x_4 = 6, \\
2x_2 - x_3 + x_4 + 4x_5 = 6.
$$

In [61]:
import numpy as np
A = np.array([[4,1,2,0,1], [-1,-3,1,1,0], [2,1,5,-1,-1], [-1,-1,-1,4,0], [2,-1,1,0,4]])
b = np.array([6,6,6,6,6])
x0 = [0, 0, 0, 0, 0]

x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_seidel

[02-05 12:44:06][INFO] i= 0 x: [[0. 0. 0. 0. 0.]]
[02-05 12:44:06][INFO] i= 1 x: [[ 1.5   -2.5    1.1    1.525 -0.15 ]]
[02-05 12:44:06][INFO] i= 2 x: [[ 1.6125   -1.6625    1.1625    1.778125 -0.0125  ]]
[02-05 12:44:06][INFO] i= 3 x: [[ 1.3375     -1.465625    1.31125     1.79578125  0.13703125]]
[02-05 12:44:06][INFO] i= 4 x: [[ 1.17652344 -1.3564974   1.3872526   1.80181966  0.22580078]]
[02-05 12:44:06][INFO] i= 5 x: [[ 1.08904785 -1.29999186  1.42990332  1.80473983  0.27300228]]
[02-05 12:44:06][INFO] i= 6 x: [[ 1.04179574 -1.26905086  1.4526403   1.80634629  0.29867934]]
[02-05 12:44:06][INFO] i= 7 x: [[ 1.01627273 -1.25242871  1.46498178  1.80720645  0.31251101]]
[02-05 12:44:06][INFO] i= 8 x: [[ 1.00248854 -1.24343344  1.47163476  1.80767247  0.31998868]]
[02-05 12:44:06][INFO] i= 9 x: [[ 0.99504381 -1.23857886  1.47523048  1.80792386  0.32402576]]
[02-05 12:44:06][INFO] i= 10 x: [[ 0.99102303 -1.23595623  1.47717196  1.80805969  0.32620644]]
[02-05 12:44:06][INFO] i= 11 x: [[

array([[ 0.98630183],
       [-1.23287701],
       [ 1.47945183],
       [ 1.80821916],
       [ 0.32876687]])

## Tercer ejercicio

3. **Utilice el método de Jacobi para resolver los sistemas lineales en el ejercicio 1, con $TOL = 10^{-3}$.**

In [62]:
tol = 1e-3

### a.

In [63]:
import numpy as np
A = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
b = np.array([1, 0, 4])
x0 = [0, 0, 0]
x_jacobi, tray_jacobi = gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_jacobi

[02-05 12:44:06][INFO] i= 0 x: [[0. 0. 0.]]
[02-05 12:44:06][INFO] i= 1 x: [[0.33333333 0.         0.57142857]]
[02-05 12:44:06][INFO] i= 2 x: [[ 0.14285714 -0.35714286  0.42857143]]
[02-05 12:44:06][INFO] i= 3 x: [[ 0.07142857 -0.21428571  0.66326531]]
[02-05 12:44:06][INFO] i= 4 x: [[ 0.04081633 -0.25680272  0.63265306]]
[02-05 12:44:06][INFO] i= 5 x: [[ 0.03684807 -0.23129252  0.66399417]]
[02-05 12:44:06][INFO] i= 6 x: [[ 0.03490444 -0.23975543  0.6547619 ]]
[02-05 12:44:06][INFO] i= 7 x: [[ 0.03516089 -0.23570619  0.65922185]]
[02-05 12:44:06][INFO] i= 8 x: [[ 0.03502399 -0.23732106  0.65737656]]
[02-05 12:44:06][INFO] i= 9 x: [[ 0.03510079 -0.23663751  0.65812732]]


array([[ 0.03507839],
       [-0.23692617],
       [ 0.65780145]])

### b.

In [64]:
import numpy as np
A = np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]])
b = np.array([9, 7, 6])
x0 = [0, 0, 0]

x_jacobi, tray_jacobi = gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_jacobi

[02-05 12:44:06][INFO] i= 0 x: [[0. 0. 0.]]
[02-05 12:44:06][INFO] i= 1 x: [[0.9 0.7 0.6]]
[02-05 12:44:06][INFO] i= 2 x: [[0.97 0.91 0.74]]
[02-05 12:44:06][INFO] i= 3 x: [[0.991 0.945 0.782]]
[02-05 12:44:06][INFO] i= 4 x: [[0.9945 0.9555 0.789 ]]
[02-05 12:44:06][INFO] i= 5 x: [[0.99555 0.95725 0.7911 ]]


array([[0.995725],
       [0.957775],
       [0.79145 ]])

### c.

In [65]:
import numpy as np
x0 = [0, 0, 0, 0]
A = np.array([[10,5,0,0], [5,10,-4,0], [0,-4,8,-1], [0,0,-1,5]])
b = np.array([6,25,-11,-11])

x_jacobi, tray_jacobi = gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_jacobi

[02-05 12:44:06][INFO] i= 0 x: [[0. 0. 0. 0.]]
[02-05 12:44:06][INFO] i= 1 x: [[ 0.6    2.5   -1.375 -2.2  ]]
[02-05 12:44:06][INFO] i= 2 x: [[-0.65   1.65  -0.4   -2.475]]
[02-05 12:44:06][INFO] i= 3 x: [[-0.225     2.665    -0.859375 -2.28    ]]
[02-05 12:44:06][INFO] i= 4 x: [[-0.7325    2.26875  -0.3275   -2.371875]]
[02-05 12:44:06][INFO] i= 5 x: [[-0.534375    2.73525    -0.53710938 -2.2655    ]]
[02-05 12:44:06][INFO] i= 6 x: [[-0.767625    2.55234375 -0.2905625  -2.30742188]]
[02-05 12:44:06][INFO] i= 7 x: [[-0.67617187  2.7675875  -0.38725586 -2.2581125 ]]
[02-05 12:44:06][INFO] i= 8 x: [[-0.78379375  2.68318359 -0.27347031 -2.27745117]]
[02-05 12:44:06][INFO] i= 9 x: [[-0.7415918   2.78250875 -0.3180896  -2.25469406]]
[02-05 12:44:06][INFO] i= 10 x: [[-0.79125437  2.74356006 -0.26558238 -2.26361792]]
[02-05 12:44:06][INFO] i= 11 x: [[-0.77178003  2.78939423 -0.28617221 -2.25311648]]
[02-05 12:44:06][INFO] i= 12 x: [[-0.79469712  2.77142113 -0.26194244 -2.25723444]]
[02-05 12:

array([[-0.79758533],
       [ 2.79479459],
       [-0.25888879],
       [-2.25187916]])

### d.

In [66]:
import numpy as np
A = np.array([[4,1,2,0,1], [-1,-3,1,1,0], [2,1,5,-1,-1], [-1,-1,-1,4,0], [2,-1,1,0,4]])
b = np.array([6,6,6,6,6])
x0 = [0, 0, 0, 0, 0]

x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_seidel

[02-05 12:44:06][INFO] i= 0 x: [[0. 0. 0. 0. 0.]]
[02-05 12:44:06][INFO] i= 1 x: [[ 1.5   -2.5    1.1    1.525 -0.15 ]]
[02-05 12:44:06][INFO] i= 2 x: [[ 1.6125   -1.6625    1.1625    1.778125 -0.0125  ]]
[02-05 12:44:06][INFO] i= 3 x: [[ 1.3375     -1.465625    1.31125     1.79578125  0.13703125]]
[02-05 12:44:06][INFO] i= 4 x: [[ 1.17652344 -1.3564974   1.3872526   1.80181966  0.22580078]]
[02-05 12:44:06][INFO] i= 5 x: [[ 1.08904785 -1.29999186  1.42990332  1.80473983  0.27300228]]
[02-05 12:44:06][INFO] i= 6 x: [[ 1.04179574 -1.26905086  1.4526403   1.80634629  0.29867934]]
[02-05 12:44:06][INFO] i= 7 x: [[ 1.01627273 -1.25242871  1.46498178  1.80720645  0.31251101]]
[02-05 12:44:06][INFO] i= 8 x: [[ 1.00248854 -1.24343344  1.47163476  1.80767247  0.31998868]]
[02-05 12:44:06][INFO] i= 9 x: [[ 0.99504381 -1.23857886  1.47523048  1.80792386  0.32402576]]
[02-05 12:44:06][INFO] i= 10 x: [[ 0.99102303 -1.23595623  1.47717196  1.80805969  0.32620644]]
[02-05 12:44:06][INFO] i= 11 x: [[

array([[ 0.98704521],
       [-1.23336186],
       [ 1.47909286],
       [ 1.80819405],
       [ 0.32836371]])

## Cuarto ejercicio

4. **Utilice el método de Gauss-Seidel para resolver los sistemas lineales en el ejercicio 1, con $TOL = 10^{-3}$.**

In [67]:
tol = 1e-3

### a.

In [68]:
import numpy as np
A = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
b = np.array([1, 0, 4])
x0 = [0, 0, 0]

x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_seidel

[02-05 12:44:07][INFO] i= 0 x: [[0. 0. 0.]]
[02-05 12:44:07][INFO] i= 1 x: [[ 0.33333333 -0.16666667  0.5       ]]
[02-05 12:44:07][INFO] i= 2 x: [[ 0.11111111 -0.22222222  0.61904762]]
[02-05 12:44:07][INFO] i= 3 x: [[ 0.05291005 -0.23280423  0.64852608]]
[02-05 12:44:07][INFO] i= 4 x: [[ 0.03955656 -0.23595364  0.65559875]]
[02-05 12:44:07][INFO] i= 5 x: [[ 0.0361492  -0.23660752  0.65733928]]


array([[ 0.03535107],
       [-0.23678863],
       [ 0.65775895]])

### b.

In [69]:
import numpy as np
A = np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]])
b = np.array([9, 7, 6])
x0 = [0, 0, 0]

x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_seidel

[02-05 12:44:07][INFO] i= 0 x: [[0. 0. 0.]]
[02-05 12:44:07][INFO] i= 1 x: [[0.9   0.79  0.758]]
[02-05 12:44:07][INFO] i= 2 x: [[0.979  0.9495 0.7899]]
[02-05 12:44:07][INFO] i= 3 x: [[0.99495  0.957475 0.791495]]


array([[0.9957475 ],
       [0.95787375],
       [0.79157475]])

### c.

In [70]:
import numpy as np
A = np.array([[10,5,0,0], [5,10,-4,0], [0,-4,8,-1], [0,0,-1,5]])
b = np.array([6,25,-11,-11])
x0 = [0, 0, 0, 0]

x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_seidel

[02-05 12:44:07][INFO] i= 0 x: [[0. 0. 0. 0.]]
[02-05 12:44:07][INFO] i= 1 x: [[ 0.6    2.2   -0.275 -2.255]]
[02-05 12:44:07][INFO] i= 2 x: [[-0.5       2.64     -0.336875 -2.267375]]
[02-05 12:44:07][INFO] i= 3 x: [[-0.72        2.72525    -0.29579687 -2.25915938]]
[02-05 12:44:07][INFO] i= 4 x: [[-0.762625    2.76299375 -0.27589805 -2.25517961]]
[02-05 12:44:07][INFO] i= 5 x: [[-0.78149687  2.78038922 -0.26670284 -2.25334057]]
[02-05 12:44:07][INFO] i= 6 x: [[-0.79019461  2.78841617 -0.26245949 -2.2524919 ]]
[02-05 12:44:07][INFO] i= 7 x: [[-0.79420808  2.79212025 -0.26050136 -2.25210027]]
[02-05 12:44:07][INFO] i= 8 x: [[-0.79606012  2.79382952 -0.25959778 -2.25191956]]
[02-05 12:44:07][INFO] i= 9 x: [[-0.79691476  2.79461827 -0.25918081 -2.25183616]]


array([[-0.79730913],
       [ 2.79498224],
       [-0.2589884 ],
       [-2.25179768]])

### d.

In [71]:
import numpy as np
A = np.array([[4,1,2,0,1], [-1,-3,1,1,0], [2,1,5,-1,-1], [-1,-1,-1,4,0], [2,-1,1,0,4]])
b = np.array([6,6,6,6,6])
x0 = [0, 0, 0, 0, 0]

x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_seidel

[02-05 12:44:07][INFO] i= 0 x: [[0. 0. 0. 0. 0.]]
[02-05 12:44:07][INFO] i= 1 x: [[ 1.5   -2.5    1.1    1.525 -0.15 ]]
[02-05 12:44:07][INFO] i= 2 x: [[ 1.6125   -1.6625    1.1625    1.778125 -0.0125  ]]
[02-05 12:44:07][INFO] i= 3 x: [[ 1.3375     -1.465625    1.31125     1.79578125  0.13703125]]
[02-05 12:44:07][INFO] i= 4 x: [[ 1.17652344 -1.3564974   1.3872526   1.80181966  0.22580078]]
[02-05 12:44:07][INFO] i= 5 x: [[ 1.08904785 -1.29999186  1.42990332  1.80473983  0.27300228]]
[02-05 12:44:07][INFO] i= 6 x: [[ 1.04179574 -1.26905086  1.4526403   1.80634629  0.29867934]]
[02-05 12:44:07][INFO] i= 7 x: [[ 1.01627273 -1.25242871  1.46498178  1.80720645  0.31251101]]
[02-05 12:44:07][INFO] i= 8 x: [[ 1.00248854 -1.24343344  1.47163476  1.80767247  0.31998868]]
[02-05 12:44:07][INFO] i= 9 x: [[ 0.99504381 -1.23857886  1.47523048  1.80792386  0.32402576]]
[02-05 12:44:07][INFO] i= 10 x: [[ 0.99102303 -1.23595623  1.47717196  1.80805969  0.32620644]]
[02-05 12:44:07][INFO] i= 11 x: [[

array([[ 0.98704521],
       [-1.23336186],
       [ 1.47909286],
       [ 1.80819405],
       [ 0.32836371]])

### Quinto Ejercicio

5. **El sistema lineal**

$$
2x_1 - x_2 + x_3 = -1, \\
2x_1 + 2x_2 + 2x_3 = 4, \\
-x_1 - x_2 + 2x_3 = -5.
$$

**tiene la solución $ (1, 2, -1)^{t} $**


### a.
Muestre que el método de Jacobi con $ x^{(0)} = 0 $ falla al proporcionar una buena aproximación después de 25 iteraciones.


In [72]:
import numpy as np
A = np.array([[2, -1, 1], [2, 2, 2], [-1, -1, 2]])
b = np.array([-1, -1, 2])
x0 = [0, 0, 0]
tol = 1e-6
max_iter = 25
x_jacobi, tray_jacobi = gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_jacobi

[02-05 12:44:07][INFO] i= 0 x: [[0. 0. 0.]]
[02-05 12:44:07][INFO] i= 1 x: [[-0.5 -0.5  1. ]]
[02-05 12:44:07][INFO] i= 2 x: [[-1.25 -1.    0.5 ]]
[02-05 12:44:07][INFO] i= 3 x: [[-1.25   0.25  -0.125]]
[02-05 12:44:07][INFO] i= 4 x: [[-0.3125  0.875   0.5   ]]
[02-05 12:44:07][INFO] i= 5 x: [[-0.3125  -0.6875   1.28125]]
[02-05 12:44:07][INFO] i= 6 x: [[-1.484375 -1.46875   0.5     ]]
[02-05 12:44:07][INFO] i= 7 x: [[-1.484375   0.484375  -0.4765625]]
[02-05 12:44:07][INFO] i= 8 x: [[-0.01953125  1.4609375   0.5       ]]
[02-05 12:44:07][INFO] i= 9 x: [[-0.01953125 -0.98046875  1.72070312]]
[02-05 12:44:07][INFO] i= 10 x: [[-1.85058594 -2.20117188  0.5       ]]
[02-05 12:44:07][INFO] i= 11 x: [[-1.85058594  0.85058594 -1.02587891]]
[02-05 12:44:07][INFO] i= 12 x: [[0.43823242 2.37646484 0.5       ]]
[02-05 12:44:07][INFO] i= 13 x: [[ 0.43823242 -1.43823242  2.40734863]]
[02-05 12:44:07][INFO] i= 14 x: [[-2.42279053 -3.34558105  0.5       ]]
[02-05 12:44:07][INFO] i= 15 x: [[-2.4227905

array([[4.01730508],
       [9.53461015],
       [0.5       ]])

### b.
Utilice el método de Gauss-Seidel con $ x^{(0)} = 0 $ para aproximar la solución para el sistema lineal dentro de $ 10^{-5}$.

In [73]:
import numpy as np
A = np.array([[2, -1, 1], [2, 2, 2], [-1, -1, 2]])
b = np.array([-1, -1, 2])
x0 = [0, 0, 0]
tol = 1e-5
max_iter = 25

x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_seidel

[02-05 12:44:07][INFO] i= 0 x: [[0. 0. 0.]]
[02-05 12:44:07][INFO] i= 1 x: [[-0.5   0.    0.75]]
[02-05 12:44:07][INFO] i= 2 x: [[-0.875 -0.375  0.375]]
[02-05 12:44:07][INFO] i= 3 x: [[-0.875   0.      0.5625]]
[02-05 12:44:07][INFO] i= 4 x: [[-0.78125 -0.28125  0.46875]]
[02-05 12:44:07][INFO] i= 5 x: [[-0.875    -0.09375   0.515625]]
[02-05 12:44:07][INFO] i= 6 x: [[-0.8046875 -0.2109375  0.4921875]]
[02-05 12:44:07][INFO] i= 7 x: [[-0.8515625  -0.140625    0.50390625]]
[02-05 12:44:07][INFO] i= 8 x: [[-0.82226562 -0.18164062  0.49804688]]
[02-05 12:44:07][INFO] i= 9 x: [[-0.83984375 -0.15820312  0.50097656]]
[02-05 12:44:07][INFO] i= 10 x: [[-0.82958984 -0.17138672  0.49951172]]
[02-05 12:44:07][INFO] i= 11 x: [[-0.83544922 -0.1640625   0.50024414]]
[02-05 12:44:07][INFO] i= 12 x: [[-0.83215332 -0.16809082  0.49987793]]
[02-05 12:44:07][INFO] i= 13 x: [[-0.83398438 -0.16589355  0.50006104]]
[02-05 12:44:07][INFO] i= 14 x: [[-0.83297729 -0.16708374  0.49996948]]
[02-05 12:44:07][INF

array([[-0.83333457],
       [-0.16666532],
       [ 0.50000006]])

### Sexto Ejercicio

6. **El sistema lineal**

$$
x_1 - x_3 = 0.2, \\
-\frac{1}{2}x_1 + x_2 - \frac{1}{4}x_3 = -1.425, \\
x_1 - \frac{1}{2}x_2 + x_3 = 2.
$$

**tiene la solución $(0.9, -0.8, 0.7)$**.


### a. 
¿La matriz de coeficientes 

$$
A = 
\begin{bmatrix}
1 & 0 & -1 \\
-\frac{1}{2} & 1 & -\frac{1}{4} \\
1 & -\frac{1}{2} & 1 
\end{bmatrix}
$$

tiene diagonal estrictamente dominante?


In [74]:
import numpy as np

def es_estrictamente_diagonal(matriz):
    filas, columnas = matriz.shape
    if filas != columnas:
        return False  

    for i in range(filas):
        for j in range(columnas):
            if i != j and matriz[i, j] != 0:
                return False  

    return True

A = np.array([[1, 0, -1],[-0.5, 1, -0.25],[1, -0.5, 1]])


print("Matriz A es estrictamente diagonal:", es_estrictamente_diagonal(A)) 


Matriz A es estrictamente diagonal: False


### b. 

Utilice el método iterativo de Gauss-Seidel para aproximar la solución para el sistema lineal con una tolerancia de $10^{-22}$ y un máximo de 300 iteraciones.


In [75]:
A = np.array([[1, 0, -1],[-0.5, 1, -0.25],[1, -0.5, 1]])
b = np.array([0.2, -1.425, 2])
x0 = [0, 0, 0]
tol = 1e-22
max_iter = 300

x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_seidel

[02-05 12:44:07][INFO] i= 0 x: [[0. 0. 0.]]
[02-05 12:44:07][INFO] i= 1 x: [[ 0.2    -1.325   1.1375]]
[02-05 12:44:07][INFO] i= 2 x: [[ 1.3375    -0.471875   0.4265625]]
[02-05 12:44:07][INFO] i= 3 x: [[ 0.6265625  -1.00507812  0.87089844]]
[02-05 12:44:07][INFO] i= 4 x: [[ 1.07089844 -0.67182617  0.59318848]]
[02-05 12:44:07][INFO] i= 5 x: [[ 0.79318848 -0.88010864  0.7667572 ]]
[02-05 12:44:07][INFO] i= 6 x: [[ 0.9667572  -0.7499321   0.65827675]]
[02-05 12:44:07][INFO] i= 7 x: [[ 0.85827675 -0.83129244  0.72607703]]
[02-05 12:44:07][INFO] i= 8 x: [[ 0.92607703 -0.78044223  0.68370185]]
[02-05 12:44:07][INFO] i= 9 x: [[ 0.88370185 -0.81222361  0.71018634]]
[02-05 12:44:07][INFO] i= 10 x: [[ 0.91018634 -0.79236024  0.69363354]]
[02-05 12:44:07][INFO] i= 11 x: [[ 0.89363354 -0.80477485  0.70397904]]
[02-05 12:44:07][INFO] i= 12 x: [[ 0.90397904 -0.79701572  0.6975131 ]]
[02-05 12:44:07][INFO] i= 13 x: [[ 0.8975131  -0.80186517  0.70155431]]
[02-05 12:44:07][INFO] i= 14 x: [[ 0.9015543

array([[ 0.9],
       [-0.8],
       [ 0.7]])

### c. 
¿Qué pasa en la parte b. cuando el sistema cambia por el siguiente?

$$
x_1 - 2x_3 = 0.2, \\
-\frac{1}{2}x_1 + x_2 - \frac{1}{4}x_3 = -1.425, \\
x_1 - \frac{1}{2}x_2 + x_3 = 2.
$$


In [76]:
A = np.array([[1, 0, -2],[-0.5, 1, -0.25],[1, -0.5, 1]])
b = np.array([0.2, -1.425, 2])
x0 = [0, 0, 0]
tol = 1e-22
max_iter = 300

x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_seidel

[02-05 12:44:08][INFO] i= 0 x: [[0. 0. 0.]]
[02-05 12:44:08][INFO] i= 1 x: [[ 0.2    -1.325   1.1375]]
[02-05 12:44:08][INFO] i= 2 x: [[ 2.475      0.096875  -0.4265625]]
[02-05 12:44:08][INFO] i= 3 x: [[-0.653125   -1.85820313  1.72402344]]
[02-05 12:44:08][INFO] i= 4 x: [[ 3.64804688  0.8300293  -1.23303223]]
[02-05 12:44:08][INFO] i= 5 x: [[-2.26606445 -2.86629028  2.83291931]]
[02-05 12:44:08][INFO] i= 6 x: [[ 5.86583862  2.21614914 -2.75776405]]
[02-05 12:44:08][INFO] i= 7 x: [[-5.31552811 -4.77220507  4.92942557]]
[02-05 12:44:08][INFO] i= 8 x: [[10.05885115  4.83678197 -5.64046016]]
[02-05 12:44:08][INFO] i= 9 x: [[-11.08092033  -8.3755752    8.89313272]]
[02-05 12:44:08][INFO] i= 10 x: [[ 17.98626545   9.79141591 -11.0905575 ]]
[02-05 12:44:08][INFO] i= 11 x: [[-21.98111499 -15.18819687  16.38701656]]
[02-05 12:44:08][INFO] i= 12 x: [[ 32.97403311  19.1587707  -21.39464777]]
[02-05 12:44:08][INFO] i= 13 x: [[-42.58929553 -28.06830971  30.55514068]]
[02-05 12:44:08][INFO] i= 14 

array([[-1.56863478e+41],
       [-9.80396739e+40],
       [ 1.07843641e+41]])

El sistema no converge en la solución dada.

## Séptimo Ejercicio

7. **Repita el ejercicio 11 usando el método de Jacobi**

### b.

In [77]:
A = np.array([[1, 0, -1],[-0.5, 1, -0.25],[1, -0.5, 1]],dtype=float)
b = np.array([0.2, -1.425, 2], dtype=float)
x0 = [0, 0, 0]
tol = 1e-22
max_iter = 300

x_jacobi, tray_jacobi = gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_jacobi

[02-05 12:44:08][INFO] i= 0 x: [[0. 0. 0.]]
[02-05 12:44:08][INFO] i= 1 x: [[ 0.2   -1.425  2.   ]]
[02-05 12:44:08][INFO] i= 2 x: [[ 2.2    -0.825   1.0875]]
[02-05 12:44:08][INFO] i= 3 x: [[ 1.2875   -0.053125 -0.6125  ]]
[02-05 12:44:08][INFO] i= 4 x: [[-0.4125    -0.934375   0.6859375]]
[02-05 12:44:08][INFO] i= 5 x: [[ 0.8859375  -1.45976563  1.9453125 ]]
[02-05 12:44:08][INFO] i= 6 x: [[ 2.1453125  -0.49570312  0.38417969]]
[02-05 12:44:08][INFO] i= 7 x: [[ 0.58417969 -0.25629883 -0.39316406]]
[02-05 12:44:08][INFO] i= 8 x: [[-0.19316406 -1.23120117  1.2876709 ]]
[02-05 12:44:08][INFO] i= 9 x: [[ 1.4876709  -1.19966431  1.57756348]]
[02-05 12:44:08][INFO] i= 10 x: [[ 1.77756348 -0.28677368 -0.08750305]]
[02-05 12:44:08][INFO] i= 11 x: [[ 0.11249695 -0.55809402  0.07904968]]
[02-05 12:44:08][INFO] i= 12 x: [[ 0.27904968 -1.34898911  1.60845604]]
[02-05 12:44:08][INFO] i= 13 x: [[ 1.80845604 -0.88336115  1.04645576]]
[02-05 12:44:08][INFO] i= 14 x: [[ 1.24645576 -0.25915804 -0.2501

array([[ 0.89979164],
       [-0.80015806],
       [ 0.70025541]])

### c.

In [78]:
A = np.array([[1, 0, -2],[-0.5, 1, -0.25],[1, -0.5, 1]], dtype=float)
b = np.array([0.2, -1.425, 2], dtype=float)
x0 = [0, 0, 0]
tol = 1e-22
max_iter = 300

x_jacobi, tray_jacobi = gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_jacobi

[02-05 12:44:09][INFO] i= 0 x: [[0. 0. 0.]]
[02-05 12:44:09][INFO] i= 1 x: [[ 0.2   -1.425  2.   ]]
[02-05 12:44:09][INFO] i= 2 x: [[ 4.2    -0.825   1.0875]]
[02-05 12:44:09][INFO] i= 3 x: [[ 2.375     0.946875 -2.6125  ]]
[02-05 12:44:09][INFO] i= 4 x: [[-5.025     -0.890625   0.0984375]]
[02-05 12:44:09][INFO] i= 5 x: [[ 0.396875   -3.91289062  6.5796875 ]]
[02-05 12:44:09][INFO] i= 6 x: [[13.359375    0.41835938 -0.35332031]]
[02-05 12:44:09][INFO] i= 7 x: [[ -0.50664063   5.16635742 -11.15019531]]
[02-05 12:44:09][INFO] i= 8 x: [[-22.10039062  -4.46586914   5.08981934]]
[02-05 12:44:09][INFO] i= 9 x: [[ 10.37963867 -11.20274048  21.86745605]]
[02-05 12:44:09][INFO] i= 10 x: [[ 43.93491211   9.23168335 -13.98100891]]
[02-05 12:44:09][INFO] i= 11 x: [[-27.76201782  17.04720383 -37.31907043]]
[02-05 12:44:09][INFO] i= 12 x: [[-74.43814087 -24.63577652  38.28561974]]
[02-05 12:44:09][INFO] i= 13 x: [[ 76.77123947 -29.0726655   64.12025261]]
[02-05 12:44:09][INFO] i= 14 x: [[128.440505

array([[-1.79225360e+43],
       [-4.51500391e+42],
       [ 6.72394565e+42]])

## Octavo Ejercicio

8. **Un cable coaxial**

Un cable coaxial está formado por un conductor interno de 0.1 pulgadas cuadradas y un conductor externo de 0.5 pulgadas cuadradas. El potencial en un punto en la sección transversal del cable se describe mediante la ecuación de Laplace.

Suponga que el conductor interno se mantiene en 0 volts y el conductor externo se mantiene en 110 volts. Aproximar el potencial entre los dos conductores requiere resolver el siguiente sistema lineal:


![](Ejercicio8.png)

### a. 
¿La matriz es estrictamente diagonalmente dominante?


In [79]:
A = np.array([
    [4, -1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0],
    [-1, 4, -1, 0, -1, 0, 0, 0, 0, 0, 0, 0],
    [0, -1, 4, 0, 0, -1, 0, 0, 0, 0, 0, 0],
    [-1, 0, 0, 4, -1, 0, -1, 0, 0, 0, 0, 0],
    [0, -1, 0, -1, 4, -1, 0, -1, 0, 0, 0, 0],
    [0, 0, -1, 0, -1, 4, 0, 0, -1, 0, 0, 0],
    [0, 0, 0, -1, 0, 0, 4, -1, 0, -1, 0, 0],
    [0, 0, 0, 0, -1, 0, -1, 4, -1, 0, -1, 0],
    [0, 0, 0, 0, 0, -1, 0, -1, 4, 0, 0, -1],
    [0, 0, 0, 0, 0, 0, -1, 0, 0, 4, -1, 0],
    [0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 4, -1],
    [0, 0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 4],
], dtype=float)

print("Matriz A es estrictamente diagonal:", es_estrictamente_diagonal(A))

Matriz A es estrictamente diagonal: False



### b.
Resuelva el sistema lineal usando el método de Jacobi con $ x^{(0)} = 0 $ y $TOL = 10^{-2} $.


In [80]:
A = np.array([
    [4, -1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0],
    [-1, 4, -1, 0, -1, 0, 0, 0, 0, 0, 0, 0],
    [0, -1, 4, 0, 0, -1, 0, 0, 0, 0, 0, 0],
    [-1, 0, 0, 4, -1, 0, -1, 0, 0, 0, 0, 0],
    [0, -1, 0, -1, 4, -1, 0, -1, 0, 0, 0, 0],
    [0, 0, -1, 0, -1, 4, 0, 0, -1, 0, 0, 0],
    [0, 0, 0, -1, 0, 0, 4, -1, 0, -1, 0, 0],
    [0, 0, 0, 0, -1, 0, -1, 4, -1, 0, -1, 0],
    [0, 0, 0, 0, 0, -1, 0, -1, 4, 0, 0, -1],
    [0, 0, 0, 0, 0, 0, -1, 0, 0, 4, -1, 0],
    [0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 4, -1],
    [0, 0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 4],
], dtype=float)

b = np.array([220, 110, 110, 220, 110, 110, 110, 110, 220, 110, 110, 220], dtype=float)
x0 = np.zeros_like(b)
tol = 1e-2
max_iter = 100

x_jacobi, tray_jacobi = gauss_jacobi(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_jacobi

[02-05 12:44:09][INFO] i= 0 x: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[02-05 12:44:09][INFO] i= 1 x: [[55.  27.5 27.5 55.  27.5 27.5 27.5 27.5 55.  27.5 27.5 55. ]]
[02-05 12:44:09][INFO] i= 2 x: [[75.625 55.    41.25  82.5   61.875 55.    55.    61.875 82.5   41.25
  55.    75.625]]
[02-05 12:44:09][INFO] i= 3 x: [[ 89.375    72.1875   55.      103.125    91.09375  73.90625  73.90625
   91.09375 103.125    55.       72.1875   89.375  ]]
[02-05 12:44:09][INFO] i= 4 x: [[ 98.828125   86.3671875  64.0234375 118.59375   112.578125   89.8046875
   89.8046875 112.578125  118.59375    64.0234375  86.3671875  98.828125 ]]
[02-05 12:44:09][INFO] i= 5 x: [[106.24023438  96.35742188  71.54296875 130.30273438 129.3359375
  101.29882812 101.29882812 129.3359375  130.30273438  71.54296875
   96.35742188 106.24023438]]
[02-05 12:44:09][INFO] i= 6 x: [[111.66503906 104.27978516  76.9140625  139.21875    141.82373047
  110.29541016 110.29541016 141.82373047 139.21875     76.9140625
  104.27978516 111.6

array([[128.91212456],
       [128.58364064],
       [ 94.17528246],
       [167.07026954],
       [181.25480916],
       [138.12290112],
       [138.12290112],
       [181.25480916],
       [167.07026954],
       [ 94.17528246],
       [128.58364064],
       [128.91212456]])


### c. 
Repita la parte b. mediante el método de Gauss-Seidel.


In [81]:
A = np.array([
    [4, -1, 0, -1, 0, 0, 0, 0, 0, 0, 0, 0],
    [-1, 4, -1, 0, -1, 0, 0, 0, 0, 0, 0, 0],
    [0, -1, 4, 0, 0, -1, 0, 0, 0, 0, 0, 0],
    [-1, 0, 0, 4, -1, 0, -1, 0, 0, 0, 0, 0],
    [0, -1, 0, -1, 4, -1, 0, -1, 0, 0, 0, 0],
    [0, 0, -1, 0, -1, 4, 0, 0, -1, 0, 0, 0],
    [0, 0, 0, -1, 0, 0, 4, -1, 0, -1, 0, 0],
    [0, 0, 0, 0, -1, 0, -1, 4, -1, 0, -1, 0],
    [0, 0, 0, 0, 0, -1, 0, -1, 4, 0, 0, -1],
    [0, 0, 0, 0, 0, 0, -1, 0, 0, 4, -1, 0],
    [0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 4, -1],
    [0, 0, 0, 0, 0, 0, 0, 0, -1, 0, -1, 4],
], dtype=float)

b = np.array([220, 110, 110, 220, 110, 110, 110, 110, 220, 110, 110, 220], dtype=float)
x0 = np.zeros_like(b)
tol = 1e-2
max_iter = 100

x_seidel, tray_seidel = gauss_seidel(A=A, b=b, x0=x0, tol=tol, max_iter=max_iter)

x_seidel

[02-05 12:44:09][INFO] i= 0 x: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[02-05 12:44:09][INFO] i= 1 x: [[55.         41.25       37.8125     68.75       55.         50.703125
  44.6875     52.421875   80.78125    38.671875   50.2734375  87.76367188]]
[02-05 12:44:09][INFO] i= 2 x: [[ 82.5         71.328125    58.0078125  100.546875    96.25
   86.25976562  75.41015625 103.17871094 124.30053711  58.92089844
   89.96582031 108.56658936]]
[02-05 12:44:09][INFO] i= 3 x: [[ 97.96875     90.55664062  71.70410156 122.40722656 128.10058594
  108.52630615  98.62670898 137.74841309 143.71032715  74.64813232
  107.74078369 117.86277771]]
[02-05 12:44:09][INFO] i= 4 x: [[108.2409668  104.51141357  80.75942993 138.74206543 149.88204956
  121.08795166 115.28465271 156.65445328 153.90129566  83.2563591
  116.94339752 122.7111733 ]]
[02-05 12:44:09][INFO] i= 5 x: [[115.81336975 114.11371231  86.30041599 150.24501801 163.02528381
  128.30674887 125.0389576  167.22723365 159.56128895  87.99558878
  121.983

array([[128.91427119],
       [128.58785536],
       [ 94.17889466],
       [167.0750917 ],
       [181.26307477],
       [138.12952091],
       [138.12874578],
       [181.26417096],
       [167.07747692],
       [ 94.17937371],
       [128.58994012],
       [128.91685426]])

**GitHub:** git@github.com: alda244



[GitHub Métodos Númericos - Repositorio](https://github.com/alda244/MN_Deberes/blob/main/PereiraAlicia_Deber11.ipynb)