# Conjunto de Ejercicios - Descomposición LU


## Primer Ejercicio

1. **Realice las siguientes multiplicaciones matriz-matriz:**


In [2]:
def matrixProduct(A, B):
    n = len(A)
    m = len(B[0])
    p = len(B)
    C = [[0 for i in range(m)] for j in range(n)]
    for i in range(n):
        for j in range(m):
            for k in range(p):
                C[i][j] += A[i][k] * B[k][j]
    return C

### a.
$ \begin{bmatrix}
2 & -3  \\
3 & -1 
 \end{bmatrix}
$
$ \begin{bmatrix}
1 & 5  \\
2 & 0 
 \end{bmatrix}
$



In [3]:
a_1 = [[2,-3],[3,-1]] 
a_2 = [[1,5],[2,0]]

print("Resultado: ", matrixProduct(a_1, a_2))

Resultado:  [[-4, 10], [1, 15]]


### b.
$ \begin{bmatrix}
2 & -3  \\
3 & -1 
 \end{bmatrix}
$
$ \begin{bmatrix}
1 & 5  & -4\\
-3 & 2 & 0
 \end{bmatrix}
$

In [4]:
b_1 = [[2,-3],[3,-1]] 
b_2 = [[1,5,-4],[-3,2,0]]

print("Resultado: ", matrixProduct(b_1, b_2))

Resultado:  [[11, 4, -8], [6, 13, -12]]


### c.
$ \begin{bmatrix}
2 & -3 & 1 \\
4 & 3 &  0 \\
5 & 2 & -4 
 \end{bmatrix}
$
$ \begin{bmatrix}
0 & 1 & -2\\
1 & 0 & -1\\
2 & 3 & -2
 \end{bmatrix}
$



In [5]:
c_1 = [[2,-3,1],[4,3,0],[5,2,-4]] 
c_2 = [[0,1,-2],[1,0,-1],[2,3,-2]]

print("Resultado: ", matrixProduct(c_1, c_2))

Resultado:  [[-1, 5, -3], [3, 4, -11], [-6, -7, -4]]


### d.
$ \begin{bmatrix}
2 & 1 & 2 \\
-2 & 3 &  0 \\
2 & -1 & 3 
 \end{bmatrix}
$
$ \begin{bmatrix}
1 & -2\\
-4 & 1\\
0 & 2
 \end{bmatrix}
$



In [6]:
d_1 = [[2,1,2],[-2,3,0],[2,-1,3]]
d_2 = [[1,-2],[-4,1],[0,2]]

print("Resultado: ", matrixProduct(d_1, d_2))

Resultado:  [[-2, 1], [-14, 7], [6, 1]]


## Segundo Ejercicio

2. **Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices:**

_Definir función para calcular el determinante._

In [7]:
from src.linear_sist_methods import descomposicion_LU
import numpy as np

def calcular_determinante_con_LU(A: np.ndarray) -> float:
    """
    Calcula el determinante de una matriz cuadrada utilizando descomposición LU.

    ## Parameters
    ``A``: matriz cuadrada.

    ## Return
    ``det``: determinante de la matriz.
    """
    if not isinstance(A, np.ndarray):
        A = np.array(A, dtype=float)

    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada."
    try:
        L, U = descomposicion_LU(A)
        det = np.prod(np.diag(U))  # Producto de los elementos de la diagonal de U
    
    except ValueError: 
        det = 0
        
    return det

[02-05 21:34:47][INFO] 2025-02-05 21:34:47.006491
[02-05 21:34:47][INFO] 2025-02-05 21:34:47.195363
[02-05 21:34:47][INFO] 2025-02-05 21:34:47.198294


_Definir función para calcular la matriz adjunta._

In [8]:
import numpy as np

def get_cofactor(matrix, i, j):
    minor = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
    return ((-1) ** (i + j)) * np.linalg.det(minor)

def adjunta(matrix):
    n = matrix.shape[0]
    adj = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            adj[j, i] = get_cofactor(matrix, i, j)
    return adj

_Definir función para calcular inversa._

In [9]:
def calcular_inversa(matrix):
    det = np.linalg.det(matrix)
    if det == 0:
        raise ValueError("La matriz no tiene inversa porque su determinante es 0.")
    
    adj = adjunta(matrix)
    inv = adj / det
    return inv

### a.
$ \begin{bmatrix}
4 & 2 & 6 \\
3 & 0 & 7 \\
-2 & -1 & -3 
 \end{bmatrix}
$



In [10]:
a_3 = np.array([[4, 2, 6], [3, 0,7], [-2, -1, -3]])
determinante = calcular_determinante_con_LU(a_3)
print("\n","Determinante: ", determinante)
if determinante != 0:
    print("Inversa: ", calcular_inversa(a_3))
else:
    print("La matriz no tiene inversa")

[02-05 21:34:47][INFO] 
[[ 4.   2.   6. ]
 [ 0.  -1.5  2.5]
 [ 0.   0.   0. ]]
[02-05 21:34:47][INFO] 
[[ 4.   2.   6. ]
 [ 0.  -1.5  2.5]
 [ 0.   0.   0. ]]

 Determinante:  0
La matriz no tiene inversa


### b.
$ \begin{bmatrix}
1 & 2 & 0 \\
2 & 1 & -1 \\
3 & 1 & 1 
 \end{bmatrix}
$


In [11]:
b_3 = np.array([[1, 2, 3], [2, 1,1], [0, -1, 1]])
determinante = calcular_determinante_con_LU(b_3)
print("\n","Determinante: ", determinante)
if determinante != 0:
    print("Inversa: \n", calcular_inversa(b_3))
else:
    print("La matriz no tiene inversa")

[02-05 21:34:47][INFO] 
[[ 2.   1.   1. ]
 [ 0.   1.5  2.5]
 [ 0.  -1.   1. ]]
[02-05 21:34:47][INFO] 
[[2.         1.         1.        ]
 [0.         1.5        2.5       ]
 [0.         0.         2.66666667]]
[02-05 21:34:47][INFO] 
[[2.         1.         1.        ]
 [0.         1.5        2.5       ]
 [0.         0.         2.66666667]]

 Determinante:  8.0
Inversa: 
 [[-0.25   0.625  0.125]
 [ 0.25  -0.125 -0.625]
 [ 0.25  -0.125  0.375]]


### c.
$ \begin{bmatrix}
1 & 1 & -1 & 1\\
1 & 2 & -4 & -2\\
2 & 1 & 1 & 5\\
-1 & 0 & -2 & -4
 \end{bmatrix}
$


In [12]:
c_3 = np.array([[1, 1, -1, 1], [1, 2, -4,-2],[2,1,1,5] ,[-1,0, -2, -4]])
determinante = calcular_determinante_con_LU(c_3)
print("\n","Determinante: ", determinante)
if determinante != 0:
    print("Inversa: \n", calcular_inversa(c_3))
else:
    print("La matriz no tiene inversa")

[02-05 21:34:47][INFO] 
[[ 2.   1.   1.   5. ]
 [ 0.   1.5 -4.5 -4.5]
 [ 0.   0.5 -1.5 -1.5]
 [ 0.   0.5 -1.5 -1.5]]
[02-05 21:34:47][INFO] 
[[ 2.   1.   1.   5. ]
 [ 0.   1.5 -4.5 -4.5]
 [ 0.   0.   0.   0. ]
 [ 0.   0.   0.   0. ]]

 Determinante:  0
La matriz no tiene inversa


### d.
$ \begin{bmatrix}
4 & 0 & 0 & 0\\
6 & 7 & 0 & 0\\
9 & 11 & 1 & 0\\
5 & 4 & 1 & 1
 \end{bmatrix}
$


In [13]:
d_3 = np.array([[4, 0, 0, 0], [6, 7, 0,0],[9,11,1,0] ,[5,4,1,1]])
determinante = calcular_determinante_con_LU(d_3)
print("\n","Determinante: ", determinante)
if determinante != 0:
    print("Inversa: \n", calcular_inversa(d_3))
else:
    print("La matriz no tiene inversa")

[02-05 21:34:47][INFO] 
[[ 9.         11.          1.          0.        ]
 [ 0.         -0.33333333 -0.66666667  0.        ]
 [ 0.         -4.88888889 -0.44444444  0.        ]
 [ 0.         -2.11111111  0.44444444  1.        ]]
[02-05 21:34:47][INFO] 
[[ 9.00000000e+00  1.10000000e+01  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -4.88888889e+00 -4.44444444e-01  0.00000000e+00]
 [ 0.00000000e+00 -5.55111512e-17 -6.36363636e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  6.36363636e-01  1.00000000e+00]]
[02-05 21:34:47][INFO] 
[[ 9.00000000e+00  1.10000000e+01  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -4.88888889e+00 -4.44444444e-01  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  6.36363636e-01  1.00000000e+00]
 [ 0.00000000e+00 -5.55111512e-17  0.00000000e+00  1.00000000e+00]]
[02-05 21:34:47][INFO] 
[[ 9.00000000e+00  1.10000000e+01  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -4.88888889e+00 -4.44444444e-01  0.00000000e+00]
 [ 0.00000000e+00  0.000000

## Tercer Ejercicio

3. **Resuelva los sistemas lineales 4 x 4 que tienen la misma matriz de coeficientes:**

### a.
$$
\begin{aligned}
x_1 - x_2 + 2x_3 - x_4 &= 6, \\
x_1 - x_3 + x_4 &= 4, \\
2x_1 + x_2 + 3x_3 - 4x_4 &= -2, \\
-x_2 + x_3 - x_4 &= 5.
\end{aligned}
$$

In [14]:
from src.linear_sist_methods import resolver_LU

In [15]:
a_4 = np.array([[1,-1,2,-1],[1,0,-1,1],[2,1,3,-4],[0,-1,1,-1]])
L,U = descomposicion_LU(a_4)
print("\n \nL:\n" , L)
print("\n \nU:\n" , U)
print("\n \nResolución:\n", resolver_LU(L,U,[6,4,-2,5]))

[02-05 21:34:47][INFO] 
[[ 2.   1.   3.  -4. ]
 [ 0.  -0.5 -2.5  3. ]
 [ 0.  -1.5  0.5  1. ]
 [ 0.  -1.   1.  -1. ]]
[02-05 21:34:47][INFO] 
[[ 2.          1.          3.         -4.        ]
 [ 0.         -1.5         0.5         1.        ]
 [ 0.          0.         -2.66666667  2.66666667]
 [ 0.          0.          0.66666667 -1.66666667]]
[02-05 21:34:47][INFO] 
[[ 2.          1.          3.         -4.        ]
 [ 0.         -1.5         0.5         1.        ]
 [ 0.          0.         -2.66666667  2.66666667]
 [ 0.          0.          0.         -1.        ]]
[02-05 21:34:47][INFO] 
[[ 2.          1.          3.         -4.        ]
 [ 0.         -1.5         0.5         1.        ]
 [ 0.          0.         -2.66666667  2.66666667]
 [ 0.          0.          0.         -1.        ]]

 
L:
 [[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.5         0.33333333  1.          0.        ]
 [ 0.          0.66666667 -0.25     

$$
\begin{aligned}
x_1 - x_2 + 2x_3 - x_4 &= 1, \\
x_1 - x_3 + x_4 &= 1, \\
2x_1 + x_2 + 3x_3 - 4x_4 &= 2, \\
-x_2 + x_3 - x_4 &= -1.
\end{aligned}
$$

In [16]:
L,U = descomposicion_LU(a_4)
print("\n \nL:\n" , L)
print("\n \nU:\n" , U)
print("\n \nResolución:\n", resolver_LU(L,U,[1,1,2,-1]))

[02-05 21:34:47][INFO] 
[[ 2.   1.   3.  -4. ]
 [ 0.  -0.5 -2.5  3. ]
 [ 0.  -1.5  0.5  1. ]
 [ 0.  -1.   1.  -1. ]]
[02-05 21:34:47][INFO] 
[[ 2.          1.          3.         -4.        ]
 [ 0.         -1.5         0.5         1.        ]
 [ 0.          0.         -2.66666667  2.66666667]
 [ 0.          0.          0.66666667 -1.66666667]]
[02-05 21:34:47][INFO] 
[[ 2.          1.          3.         -4.        ]
 [ 0.         -1.5         0.5         1.        ]
 [ 0.          0.         -2.66666667  2.66666667]
 [ 0.          0.          0.         -1.        ]]
[02-05 21:34:47][INFO] 
[[ 2.          1.          3.         -4.        ]
 [ 0.         -1.5         0.5         1.        ]
 [ 0.          0.         -2.66666667  2.66666667]
 [ 0.          0.          0.         -1.        ]]

 
L:
 [[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.5         0.33333333  1.          0.        ]
 [ 0.          0.66666667 -0.25     

## Cuarto Ejercicio

4. **Encuentre los valores de A que hacen que la siguiente matriz sea singular.**

$$
A = \begin{bmatrix}
1 & -1 & \alpha \\
2 & 2 & 1 \\
0 & \alpha & -\frac{3}{2}
\end{bmatrix}
$$


_Para saber si la matriz es singular es necesario calcular su determinante, en caso de que este sea igual a cero, la matriz será singular._

- En primer lugar, se realiza cero hacia abajo en la primera columna usando operaciones entre filas para facilitar el cálculo del determinante.

$$
F2-2*F1 \rightarrow F2
$$

$$
\equiv
A = \begin{bmatrix}
1 & -1 & \alpha \\
0 & 4 & 1 - 2 \alpha \\
0 & \alpha & -\frac{3}{2}
\end{bmatrix}
$$

- Ahora es posible calcular el determinante utilizando el método del _menor de una matriz_.

$$
\det(A) = 1 \cdot \begin{vmatrix} 
4 & -2\alpha + 1 \\ 
\alpha & -\frac{3}{2} 
\end{vmatrix}
$$

- Desarrollo del determinante de la submatriz

$$
\begin{vmatrix} 
4 & -2\alpha + 1 \\ 
\alpha & -\frac{3}{2} 
\end{vmatrix}
= (4)(-\frac{3}{2}) - (-2\alpha + 1)(\alpha)
$$

$$
= -6 - (-2\alpha^2 + \alpha)
$$

$$
= -6 + 2\alpha^2 - \alpha
$$

- Sustitución en la ecuación del determinante

$$
\det(A) = 1 \cdot (2\alpha^2 - \alpha - 6)
$$

Por lo tanto, el determinante de \( A \) es:

$$
\det(A) = 2\alpha^2 - \alpha - 6
$$


- Determinación de singularidad

Para que \( A \) sea singular:

$$
2\alpha^2 - \alpha - 6 = 0
$$

- Factorizando los términos y resolviendo la ecuación:

$$
(2\alpha - 4)(\alpha + \frac{3}{2}) = 0
$$

$$
\alpha_1 = 2, \quad \alpha_2 = -\frac{3}{2}
$$

## Quinto Ejercicio

5. **Resuelva los siguientes sistemas lineales:**

### a.
$$
\begin{bmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
-1 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
2 & 3 & -1 \\
0 & -2 & 1 \\
0 & 0 & 3
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
=
\begin{bmatrix}
2 \\
-1 \\
1
\end{bmatrix}
$$


In [28]:
L = np.array(
    [[1, 0, 0],
     [2, 1, 0],
     [-1, 0, 1]]
)

U = np.array(
    [[2, 3, -1],
     [0, -2, 1],
     [0, 0, 3]]
)

print("\n \nResolución:\n", resolver_LU(L,U,[2,-1,1]))

[02-05 21:34:55][INFO] Sustitución hacia adelante
[02-05 21:34:55][INFO] y = 
[[ 2.]
 [-5.]
 [ 3.]]
[02-05 21:34:55][INFO] Sustitución hacia atrás
[02-05 21:34:55][INFO] i = 1
[02-05 21:34:55][INFO] suma = [1.]
[02-05 21:34:55][INFO] U[i, i] = -2
[02-05 21:34:55][INFO] y[i] = [-5.]
[02-05 21:34:55][INFO] i = 0
[02-05 21:34:55][INFO] suma = [8.]
[02-05 21:34:55][INFO] U[i, i] = 2
[02-05 21:34:55][INFO] y[i] = [2.]

 
Resolución:
 [[-3.]
 [ 3.]
 [ 1.]]


### b.
$$
\begin{bmatrix}
2 & 0 & 0 \\
-1 & 1 & 0 \\
3 & 2 & -1
\end{bmatrix}
\begin{bmatrix}
1 & 1 & 1 \\
0 & 1 & 2 \\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
=
\begin{bmatrix}
-1 \\
3 \\
0
\end{bmatrix}
$$

In [30]:
L2 = np.array(
    [[2, 0, 0],
     [-1, 1, 0],
     [3, 2, -1]]
)

U2 = np.array(
    [[1, 1, 1],
     [0, 1, 2],
     [0, 0, 1]]
)

print("\n \nResolución:\n", resolver_LU(L2,U2,[-1,3,0]))

[02-05 21:36:10][INFO] Sustitución hacia adelante
[02-05 21:36:10][INFO] y = 
[[-0.5]
 [ 2.5]
 [ 3.5]]
[02-05 21:36:10][INFO] Sustitución hacia atrás
[02-05 21:36:10][INFO] i = 1
[02-05 21:36:10][INFO] suma = [7.]
[02-05 21:36:10][INFO] U[i, i] = 1
[02-05 21:36:10][INFO] y[i] = [2.5]
[02-05 21:36:10][INFO] i = 0
[02-05 21:36:10][INFO] suma = [-1.]
[02-05 21:36:10][INFO] U[i, i] = 1
[02-05 21:36:10][INFO] y[i] = [-0.5]

 
Resolución:
 [[ 0.5]
 [-4.5]
 [ 3.5]]


## Sexto Ejercicio

6. **Factorice las siguientes matrices en la descomposición LU mediante el algoritmo de factorización LU con $l_{ii}$ = 1 para todas las $i$**. 

In [18]:
def lu_decomposition(A):
    """
    Realiza la descomposición LU de la matriz A utilizando el algoritmo de Doolittle.
    La matriz L tendrá 1s en la diagonal principal.
    
    Parameters:
    A (np.ndarray): Matriz cuadrada a descomponer.
    
    Returns:
    L (np.ndarray): Matriz triangular inferior con 1s en la diagonal principal.
    U (np.ndarray): Matriz triangular superior.
    """
    n = A.shape[0]
    L = np.eye(n)  # Matriz identidad de tamaño n
    U = np.zeros((n, n))
    
    for i in range(n):
        for j in range(i, n):
            U[i, j] = A[i, j] - sum(L[i, k] * U[k, j] for k in range(i))
        
        for j in range(i + 1, n):
            L[j, i] = (A[j, i] - sum(L[j, k] * U[k, i] for k in range(i))) / U[i, i]
    
    return L, U

### a.
$$
\begin{bmatrix}
2 & -1 & 1 \\
3 & 3 & 9 \\
3 & 3 & 5
\end{bmatrix}
$$


In [19]:
import numpy as np
a_4 = np.array([[2,-1,1],[3,3,9],[3,3,5]])
L,U = lu_decomposition(a_4)

print("\n \nL:\n" , L)
print("\n \nU:\n" , U)


 
L:
 [[1.  0.  0. ]
 [1.5 1.  0. ]
 [1.5 1.  1. ]]

 
U:
 [[ 2.  -1.   1. ]
 [ 0.   4.5  7.5]
 [ 0.   0.  -4. ]]


### b.
$$
\begin{bmatrix}
1.012 & -2.132 & 3.104 \\
-2.132 & 4.096 & -7.013 \\
3.104 & -7.013 & 0.014
\end{bmatrix}
$$


In [20]:
import numpy as np
b_4 = np.array([[1.012,-2.132,3.104],[-2.132,4.096,-7.013],[3.104,-7.013,0.014]])
L,U = lu_decomposition(b_4)

print("\n \nL:\n" , L)
print("\n \nU:\n" , U)


 
L:
 [[ 1.          0.          0.        ]
 [-2.10671937  1.          0.        ]
 [ 3.06719368  1.19775553  1.        ]]

 
U:
 [[ 1.012      -2.132       3.104     ]
 [ 0.         -0.39552569 -0.47374308]
 [ 0.          0.         -8.93914077]]


### c.
$$
\begin{bmatrix}
2 & 0 & 0 & 0 \\
1 & 1.5 & 0 & 0 \\
0 & -3 & 0.5 & 0 \\
2 & -2 & 1 & 1
\end{bmatrix}
$$



In [21]:
c_4 = np.array([[2, 0, 0, 0],
    [1, 1.5, 0, 0],
    [0, -3, 0.5, 0],
    [2, -2, 1, 1]])

L,U = lu_decomposition(c_4)

print("\n \nL:\n" , L)
print("\n \nU:\n" , U)


 
L:
 [[ 1.          0.          0.          0.        ]
 [ 0.5         1.          0.          0.        ]
 [ 0.         -2.          1.          0.        ]
 [ 1.         -1.33333333  2.          1.        ]]

 
U:
 [[2.  0.  0.  0. ]
 [0.  1.5 0.  0. ]
 [0.  0.  0.5 0. ]
 [0.  0.  0.  1. ]]


### d.
$$
\begin{bmatrix}
2.1756 & 4.0231 & -2.1732 & 5.1967 \\
-4.0231 & 6.0000 & 0 & 1.1973 \\
-1.0000 & -5.2107 & 1.1111 & 0 \\
6.0235 & 7.0000 & 0 & -4.1561
\end{bmatrix}
$$


In [22]:
d_4 = np.array([[2.1756, 4.0231, -2.1732, 5.1967],
    [-4.0231, 6.0000, 0, 1.1973],
    [-1.0000, -5.2107, 1.1111, 0],
    [6.0235, 7.0000, 0, -4.1561]])

L,U = lu_decomposition(d_4)

print("\n \nL:\n" , L)
print("\n \nU:\n" , U)


 
L:
 [[ 1.          0.          0.          0.        ]
 [-1.84919103  1.          0.          0.        ]
 [-0.45964332 -0.25012194  1.          0.        ]
 [ 2.76866152 -0.30794361 -5.35228302  1.        ]]

 
U:
 [[ 2.1756      4.0231     -2.1732      5.1967    ]
 [ 0.         13.43948042 -4.01866194 10.80699101]
 [ 0.          0.         -0.89295239  5.09169403]
 [ 0.          0.          0.         12.03612803]]


## Séptimo Ejercicio

7. **Modifique el algoritmo de eliminación gaussiana de tal forma que se pueda utilizar para resolver un sistema lineal usando la descomposición LU y, a continuación, resuelva los siguientes sistemas lineales.**

In [23]:
def eliminacion_gaussiana_resolver(L: np.ndarray, U: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Resuelve un sistema lineal dado L y U de una descomposición LU.

    Parameters:
        L (np.ndarray): Matriz triangular inferior de la descomposición LU.
        U (np.ndarray): Matriz triangular superior de la descomposición LU.
        b (np.ndarray): Vector de términos independientes.

    Returns:
        np.ndarray: Vector solución del sistema.
    """
    n = L.shape[0]
    y = np.zeros(n)

    # Resolución de Ly = b (sustitución hacia adelante)
    for i in range(n):
        y[i] = b[i] - np.dot(L[i, :i], y[:i])

    x = np.zeros(n)

    # Resolución de Ux = y (sustitución hacia atrás)
    for i in range(n - 1, -1, -1):
        x[i] = (y[i] - np.dot(U[i, i + 1:], x[i + 1:])) / U[i, i]

    return x

## a.

$$
\begin{aligned}
2x_1 - x_2 + x_3 &= -1, \\
3x_1 + 3x_2 + 9x_3 &= 0, \\
3x_1 + 3x_2 + 5x_3 &= 4.
\end{aligned}
$$



In [24]:
sis_a = np.array([[2,-1,1],[3,3,9],[3,3,5]])
ind_a= np.array([-1,0,4])

L,U = descomposicion_LU(sis_a)
print("\n \nL:\n" , L)
print("\n \nU:\n" , U)
r = eliminacion_gaussiana_resolver(L,U,ind_a)
print("\n \n Resolución: ", r )

[02-05 21:34:47][INFO] 
[[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]
[02-05 21:34:47][INFO] 
[[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]
[02-05 21:34:47][INFO] 
[[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]

 
L:
 [[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 1.         -0.          1.        ]]

 
U:
 [[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]

 
 Resolución:  [ 1.55555556  1.86111111 -1.25      ]


## b.

$$
\begin{aligned}
1.012x_1 - 2.132x_2 + 3.104x_3 &= 1.984, \\
-2.132x_1 + 4.096x_2 - 7.013x_3 &= -5.049, \\
3.104x_1 - 7.013x_2 + 0.014x_3 &= -3.895.
\end{aligned}
$$



In [25]:
sis_b = np.array([[1.012,-2.132,3.104],[-2.132,4.096,-7.013],[3.104,-7.013,0.014]])
ind_b= np.array([1.984,-5.049,-3.985])

L,U = descomposicion_LU(sis_b)
print("\n \nL:\n" , L)
print("\n \nU:\n" , U)
r = eliminacion_gaussiana_resolver(L,U,ind_b)
print("\n \n Resolución: ", r )

[02-05 21:34:47][INFO] 
[[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.1544549   3.09943557]]
[02-05 21:34:47][INFO] 
[[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.          1.59897957]]
[02-05 21:34:47][INFO] 
[[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.          1.59897957]]

 
L:
 [[ 1.          0.          0.        ]
 [-0.68685567  1.          0.        ]
 [ 0.32603093 -0.21424728  1.        ]]

 
U:
 [[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.          1.59897957]]

 
 Resolución:  [86.62721983 38.05210622 -3.39067526]


## c.

$$
\begin{aligned}
2x_1 &= 3, \\
x_1 + 1.5x_2 &= 4.5, \\
-3x_2 + 0.5x_3 &= -6.6, \\
2x_1 - 2x_2 + x_3 + x_4 &= 0.8.
\end{aligned}
$$


In [26]:
sis_c = np.array([[2,0,0,0],[1,1.5,0,0],[0,-3,0.5,0],[2,-2,1,1]])
ind_c= np.array([3,4.5,-6.6,0.8])

L,U = descomposicion_LU(sis_c)
print("\n \nL:\n" , L)
print("\n \nU:\n" , U)
r = eliminacion_gaussiana_resolver(L,U,ind_c)
print("\n \n Resolución: ", r )

[02-05 21:34:47][INFO] 
[[ 2.   0.   0.   0. ]
 [ 0.   1.5  0.   0. ]
 [ 0.  -3.   0.5  0. ]
 [ 0.  -2.   1.   1. ]]
[02-05 21:34:47][INFO] 
[[ 2.          0.          0.          0.        ]
 [ 0.         -3.          0.5         0.        ]
 [ 0.          0.          0.25        0.        ]
 [ 0.          0.          0.66666667  1.        ]]
[02-05 21:34:47][INFO] 
[[ 2.          0.          0.          0.        ]
 [ 0.         -3.          0.5         0.        ]
 [ 0.          0.          0.66666667  1.        ]
 [ 0.          0.          0.         -0.375     ]]
[02-05 21:34:47][INFO] 
[[ 2.          0.          0.          0.        ]
 [ 0.         -3.          0.5         0.        ]
 [ 0.          0.          0.66666667  1.        ]
 [ 0.          0.          0.         -0.375     ]]

 
L:
 [[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 1.          0.66666667  1.          0.        ]
 [ 0.5        -0.5         0.375    

## d.

$$
\begin{aligned}
2.1756x_1 + 4.0231x_2 - 2.1732x_3 + 5.1967x_4 &= 17.102, \\
-4.0231x_1 + 6.0000x_2 + 1.1973x_4 &= -6.1593, \\
-1.0000x_1 - 5.2107x_2 + 1.1111x_3 &= 3.0004, \\
6.0235x_1 + 7.0000x_2 - 4.1561x_4 &= 0.0000.
\end{aligned}
$$



In [27]:
sis_d = np.array([[2.1756,4.0231,-2.1732,5.1967],[-4.0231,6.0000,0,1.1973],[-1.0000,-5.2107,1.1111,0],[6.0235,7.0000,0,-4.1561]])
ind_d= np.array([17.102,-6.1593,3.0004,0.0000])

L,U = descomposicion_LU(sis_d)
print("\n \nL:\n" , L)
print("\n \nU:\n" , U)
r = eliminacion_gaussiana_resolver(L,U,ind_d)
print("\n \n Resolución: ", r )

[02-05 21:34:47][INFO] 
[[ 6.0235      7.          0.         -4.1561    ]
 [ 0.         10.67530506  0.         -1.57856219]
 [ 0.         -4.04858495  1.1111     -0.68998091]
 [ 0.          1.4948025  -2.1732      6.69782246]]
[02-05 21:34:47][INFO] 
[[ 6.0235      7.          0.         -4.1561    ]
 [ 0.         10.67530506  0.         -1.57856219]
 [ 0.          0.          1.1111     -1.288647  ]
 [ 0.          0.         -2.1732      6.91885959]]
[02-05 21:34:47][INFO] 
[[ 6.0235      7.          0.         -4.1561    ]
 [ 0.         10.67530506  0.         -1.57856219]
 [ 0.          0.         -2.1732      6.91885959]
 [ 0.          0.          0.          2.24878393]]
[02-05 21:34:47][INFO] 
[[ 6.0235      7.          0.         -4.1561    ]
 [ 0.         10.67530506  0.         -1.57856219]
 [ 0.          0.         -2.1732      6.91885959]
 [ 0.          0.          0.          2.24878393]]

 
L:
 [[ 1.          0.          0.          0.        ]
 [-0.66790072  1.         

**GitHub:** git@github.com: alda244



[GitHub Métodos Númericos - Repositorio](https://github.com/alda244/MN_Deberes/blob/main/PereiraAlicia_Deber10.ipynb)